# Generated by Django 3.2.7 on 2022-04-26 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cie10nativo',
            fields=[
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('CIE_10_Id', models.CharField(db_column='CIE_10_Id', max_length=5, primary_key=True, serialize=False)),
                ('CIE10_DESC', models.CharField(blank=True, db_column='CIE10_DESC', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='codigossancor',
            fields=[
                ('id', models.BigIntegerField(blank=True, null=True)),
                ('Presta_Id', models.CharField(db_column='Presta_Id', max_length=20, primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=400, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='prestaxcie10',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('Presta_Id', models.ForeignKey(blank=True, db_column='Presta_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.codigossancor')),
                ('CIE_10_Id', models.ForeignKey(blank=True, db_column='CIE_10_Id', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='principal.cie10nativo')),
            ],
        ),
    ]
