# Generated by Django 3.2.7 on 2022-04-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestaxcie10',
            name='CIE_10_Id',
        ),
        migrations.RemoveField(
            model_name='prestaxcie10',
            name='Presta_Id',
        ),
        migrations.AddField(
            model_name='cie10nativo',
            name='codigossancors',
            field=models.ManyToManyField(through='principal.prestaxcie10', to='principal.codigossancor'),
        ),
        migrations.AddField(
            model_name='codigossancor',
            name='cie10nativos',
            field=models.ManyToManyField(through='principal.prestaxcie10', to='principal.cie10nativo'),
        ),
        migrations.AddField(
            model_name='prestaxcie10',
            name='prestacion_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.codigossancor'),
        ),
        migrations.AddField(
            model_name='prestaxcie10',
            name='codCIE10_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.cie10nativo'),
        ),        
        migrations.AlterField(
            model_name='cie10nativo',
            name='CIE10_DESC',
            field=models.CharField(blank=True, db_column='CIE10_DESC', max_length=400, null=True, verbose_name='Descripción CIE 10'),
        ),
        migrations.AlterField(
            model_name='cie10nativo',
            name='CIE_10_Id',
            field=models.CharField(db_column='CIE_10_Id', max_length=5, primary_key=True, serialize=False, verbose_name='Código CIE 10 4 dígitos'),
        ),
        migrations.AlterField(
            model_name='codigossancor',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=400, null=True, verbose_name='Descripción prestación Sancor'),
        ),
        migrations.AlterField(
            model_name='codigossancor',
            name='Presta_Id',
            field=models.CharField(db_column='Presta_Id', max_length=20, primary_key=True, serialize=False, verbose_name='Código prestación Sancor'),
        ),
    ]
